DATASET:
  NAME: 'voc'
  NUM_CLASSES: 20
  DATAROOT: 'data/VOCdevkit/VOC2012/'
  SCALE: [2048, 336]
  RATIO_RANGE: [0.5, 2.0]
  CROP_SIZE: [512, 512]
  CAT_MAX_RATIO: 0.75
  IMG_NORM_CFG:
#    MEAN: [123.675, 116.28, 103.53]
#    STD: [58.395, 57.12, 57.375]
#    RGB: True
    MEAN: [ 122.771, 116.746, 104.094 ]
    STD: [ 68.501, 66.632, 70.323 ]
    RGB: True
  TEXT_WEIGHT: 'text/voc_ViT16_clip_text.pth'
  REDUCE_ZERO_LABEL: TRUE
  PALETTE: [[128, 0, 0], [0, 128, 0], [128, 128, 0], [0, 0, 128],
               [128, 0, 128], [0, 128, 128], [128, 128, 128], [64, 0, 0],
               [192, 0, 0], [64, 128, 0], [192, 128, 0], [64, 0, 128],
               [192, 0, 128], [64, 128, 128], [192, 128, 128], [0, 64, 0],
               [128, 64, 0], [0, 192, 0], [128, 192, 0], [0, 64, 128]]

MODEL:
  FEATURE_EXTRACTOR: 'vit'
  TEXT_CHANNEL: 512
  VISUAL_CHANNEL: 768
  TRAINING: False

TEST:
  BATCH_SIZE: 1
  PD: 1.0

EVAL_METRIC: "miou"
SAVE_DIR: "experiments/voc_rectification/"
LOAD_PATH: "experiments/voc_rectification/best_weight.pth"
NUM_WORKERS: 4